const API = 'https://cambo-store-api.phanhaotdg.workers.dev';
const REPO = '/pinkie/';
const BASE = location.hostname.includes('github.io') ? REPO : '/';
const $ = id => document.getElementById(id);
const qs = s => document.querySelector(s);
const token = () => localStorage.getItem('token') || '';
const go = page => location.href = BASE + page;
const pageUrl = page => BASE + page;
const esc = s => String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(msg){let t=$('toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.appendChild(t)}t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function setLoading(btn,on=true){if(!btn)return;btn.disabled=on;btn.dataset.old ||= btn.textContent;btn.textContent=on?'Please wait...':btn.dataset.old}
function applyTheme(){document.documentElement.dataset.theme=localStorage.getItem('theme')||'dark'}
function toggleTheme(){localStorage.setItem('theme',(localStorage.getItem('theme')||'dark')==='dark'?'light':'dark');applyTheme()}applyTheme();
async function api(path,opt={}){const isForm=opt.body instanceof FormData;const baseHeaders=isForm?{}:{'content-type':'application/json'};if(token())baseHeaders.authorization='Bearer '+token();const headers={...baseHeaders,...(opt.headers||{})};if(headers.authorization==='')delete headers.authorization;try{const r=await fetch(API+path,{...opt,headers});const j=await r.json().catch(()=>({ok:false,error:'Bad server response'}));if(!j.ok && j.error)toast(j.error);return j}catch(e){console.error(e);toast('Cannot connect to server');return{ok:false,error:'Network error'}}}
async function upload(file){if(!file)return'';const fd=new FormData();fd.append('file',file);const j=await api('/api/upload',{method:'POST',body:fd});return j.url||''}
async function publicUpload(file){if(!file)return'';const fd=new FormData();fd.append('file',file);const r=await fetch(API+'/api/public-upload',{method:'POST',body:fd});const j=await r.json().catch(()=>({}));return j.url||''}
async function hydrateNav(){const authLinks=document.querySelectorAll('[data-auth]');if(!token()){authLinks.forEach(a=>a.textContent='Login');return}const me=await api('/api/me');if(me.ok){authLinks.forEach(a=>{a.textContent='Dashboard';a.href=pageUrl('panel.html')})}}
async function register(){const btn=event?.target;setLoading(btn,true);const name=$('name')?.value.trim(),email=$('email')?.value.trim(),password=$('password')?.value.trim();if(!name||!email||!password){toast('Please fill all fields');setLoading(btn,false);return}const j=await api('/api/register',{method:'POST',body:JSON.stringify({name,email,password})});setLoading(btn,false);if(j.ok){toast('Account created');localStorage.setItem('last_email',email);setTimeout(()=>go('login.html'),700)}}
async function login(){const btn=event?.target;setLoading(btn,true);const email=$('email')?.value.trim(),password=$('password')?.value.trim();if(!email||!password){toast('Please fill all fields');setLoading(btn,false);return}const j=await api('/api/login',{method:'POST',body:JSON.stringify({email,password})});setLoading(btn,false);if(j.ok){localStorage.setItem('token',j.token);toast('Welcome back');setTimeout(()=>go('panel.html'),500)}}
function logout(){localStorage.removeItem('token');go('login.html')}
async function requireAuth(){if(!token()){go('login.html');return null}const me=await api('/api/me');if(!me.ok){localStorage.removeItem('token');go('login.html');return null}return me.user}
let currentSite=null;
async function loadPanel(){const u=await requireAuth();if(!u)return;$('userName').textContent=u.name;$('userEmail').textContent=u.email;$('planName').textContent=(u.role==='admin'?'ADMIN':u.plan).toUpperCase();$('planBadge').className='badge '+(u.plan==='pro'||u.role==='admin'?'pro':'');if(u.role==='admin')$('adminLink').style.display='block';if(u.role==='admin'||u.plan==='pro'){$('upgradeBtn').textContent='PRO ACTIVE';$('upgradeBtn').disabled=true;$('proStatus').textContent='Your store builder is unlocked.'}else if(u.plan_request==='pending'){$('upgradeBtn').textContent='PENDING REVIEW';$('upgradeBtn').disabled=true;$('proStatus').textContent='Admin is checking your QR proof.'}const j=await api('/api/sites');$('sites').innerHTML=(j.sites||[]).map(s=>`<div class="row"><div><b>${esc(s.title)}</b><br><span class="small">${location.hostname.includes('github.io')?location.origin+BASE+'site.html?slug='+esc(s.slug):'khstore.online/'+esc(s.slug)}</span></div><div class="row-actions"><button class="btn" onclick='editSite(${JSON.stringify(s).replaceAll("'","&apos;")})'>Builder</button><a class="ghost" href="${pageUrl('site.html?slug='+s.slug)}" target="_blank">Open</a><button class="ghost" onclick="delSite(${s.id})">Delete</button></div></div>`).join('')||'<p class="small">No store yet. Create your first website.</p>'}
async function requestPro(){const proof=$('proProof')?.files[0];let proofUrl='';if(proof)proofUrl=await upload(proof);const j=await api('/api/upgrade/request',{method:'POST',body:JSON.stringify({proof_url:proofUrl,amount:5})});if(j.ok){toast('Pro request sent to admin');loadPanel()}}
async function createSite(){const title=$('siteTitle').value.trim(),slug=$('siteSlug').value.trim().toLowerCase().replace(/[^a-z0-9-]/g,''),description=$('siteDesc').value.trim(),template=$('siteTemplate').value;if(!title||!slug){toast('Title and slug required');return}const j=await api('/api/sites',{method:'POST',body:JSON.stringify({title,slug,description,template})});if(j.ok){toast('Website created');loadPanel()}}
async function delSite(id){if(confirm('Delete this website?')){const j=await api('/api/sites/'+id,{method:'DELETE'});if(j.ok)loadPanel()}}
function initDrops(){document.querySelectorAll('.upload-zone').forEach(z=>{const input=z.querySelector('input[type=file]');z.onclick=()=>input?.click();z.ondragover=e=>{e.preventDefault();z.classList.add('drag')};z.ondragleave=()=>z.classList.remove('drag');z.ondrop=e=>{e.preventDefault();z.classList.remove('drag');if(input&&e.dataTransfer.files[0]){input.files=e.dataTransfer.files;toast('File selected')}}})}
async function editSite(s){currentSite=s;$('editor').style.display='grid';$('eTemplate').value=s.template||'emerald';$('eTitle').value=s.title||'';$('eHero').value=s.hero_name||s.title||'';$('eDesc').value=s.description||'';$('eBg').value=s.background_color||'#070a16';$('eBtn').value=s.button_color||'#ff3df2';$('eText').value=s.text_color||'#ffffff';$('eAccent').value=s.accent_color||'#35e9ff';$('notifyType').value=s.notify_type||'discord';$('discordWebhook').value=s.discord_webhook||'';$('telegramChat').value=s.telegram_chat_id||'';$('openPublic').href=pageUrl('site.html?slug='+s.slug);renderPreview();loadItems();initDrops();$('editor').scrollIntoView({behavior:'smooth'})}
function renderPreview(){if(!currentSite)return;const bg=$('eBg').value,btn=$('eBtn').value,text=$('eText').value,accent=$('eAccent').value;$('livePreview').style.background=bg;$('livePreview').style.color=text;$('livePreview').innerHTML=`<div class="preview-hero"><h2>${esc($('eHero').value||'Cambo Store')}</h2><p>${esc($('eDesc').value||'Minecraft shop')}</p><button class="btn" style="background:${btn};color:${text};box-shadow:0 0 28px ${accent}">Add to Cart</button></div><div class="mini-grid"><div class="mini-card"><b>VIP Rank</b><span class="small">$5.00</span></div><div class="mini-card"><b>Crate Key</b><span class="small">$1.00</span></div></div>`}
document.addEventListener('input',e=>{if(['eBg','eBtn','eText','eAccent','eHero','eDesc'].includes(e.target.id))renderPreview()});
async function saveSite(){let logo=currentSite.logo_url,banner=currentSite.banner_url,qr=currentSite.qr_url;if($('logoFile').files[0])logo=await upload($('logoFile').files[0]);if($('bannerFile').files[0])banner=await upload($('bannerFile').files[0]);if($('qrFile').files[0])qr=await upload($('qrFile').files[0]);const data={template:$('eTemplate').value,title:$('eTitle').value,hero_name:$('eHero').value,description:$('eDesc').value,background_color:$('eBg').value,button_color:$('eBtn').value,text_color:$('eText').value,accent_color:$('eAccent').value,logo_url:logo,banner_url:banner,qr_url:qr,notify_type:$('notifyType').value,discord_webhook:$('discordWebhook').value,telegram_chat_id:$('telegramChat').value};const j=await api('/api/sites/'+currentSite.id,{method:'PUT',body:JSON.stringify(data)});if(j.ok){currentSite={...currentSite,...data};toast('Saved');renderPreview();loadPanel()}}
async function addItem(){if(!currentSite)return;const img=await upload($('itemImage').files[0]);const j=await api(`/api/sites/${currentSite.id}/items`,{method:'POST',body:JSON.stringify({name:$('itemName').value,price:$('itemPrice').value,description:$('itemDesc').value,image_url:img,button_text:$('itemButton').value||'Add to Cart'})});if(j.ok){['itemName','itemPrice','itemDesc','itemButton'].forEach(id=>$(id).value='');$('itemImage').value='';loadItems();toast('Item added')}}
async function loadItems(){const j=await api(`/api/sites/${currentSite.id}/items`);$('items').innerHTML=(j.items||[]).map(i=>`<div class="item-card">${i.image_url?`<img src="${i.image_url}">`:''}<h3>${esc(i.name)}</h3><p class="small">${esc(i.description)}</p><b>$${esc(i.price)}</b><button class="ghost full" onclick="delItem(${i.id})">Delete</button></div>`).join('')||'<p class="small">No items yet.</p>'}
async function delItem(id){const j=await api('/api/items/'+id,{method:'DELETE'});if(j.ok)loadItems()}
async function loadAdmin(){const u=await requireAuth();if(!u)return;const j=await api('/api/admin/users');if(!j.ok)return;$('users').innerHTML=(j.users||[]).map(u=>`<div class="row"><div><b>${esc(u.name)}</b><br><span class="small">${esc(u.email)} • ${esc(u.role)} • request: ${esc(u.plan_request)}</span>${u.proof_url?`<br><a class="small" target="_blank" href="${u.proof_url}">View Pro QR proof</a>`:''}</div><div class="row-actions"><span class="badge ${u.plan==='pro'?'pro':''}">${u.plan.toUpperCase()}</span><button class="btn cyan" onclick="setPlan(${u.id},'pro')">Approve Pro</button><button class="ghost" onclick="setPlan(${u.id},'free')">Set Free</button><button class="ghost" onclick="makeAdmin(${u.id})">Admin</button></div></div>`).join('')}
async function setPlan(id,plan){const j=await api('/api/admin/users/'+id+'/plan',{method:'PUT',body:JSON.stringify({plan})});if(j.ok){toast('User updated');loadAdmin()}}
async function makeAdmin(id){const j=await api('/api/admin/users/'+id+'/role',{method:'PUT',body:JSON.stringify({role:'admin'})});if(j.ok){toast('Admin role set');loadAdmin()}}
let publicSite=null,publicItems=[],cart=[],otpToken='';
function slugFromUrl(){const q=new URLSearchParams(location.search).get('slug');if(q)return q;return location.pathname.split('/').filter(Boolean).pop()||''}
async function loadPublic(){const slug=slugFromUrl();const j=await api('/api/public/'+slug,{headers:{authorization:''}});if(!j.ok){$('publicSite').innerHTML='<div class="panel"><h1>Store not found</h1><p class="small">Check the link or slug.</p></div>';return}publicSite=j.site;publicItems=j.items||[];document.title=publicSite.title;document.documentElement.style.setProperty('--pink',publicSite.button_color||'#ff3df2');renderPublic()}
function renderPublic(){const s=publicSite;document.body.style.background=s.background_color||'';document.body.style.color=s.text_color||'';$('publicSite').innerHTML=`<div class="shop-layout"><aside class="shop-side">${s.logo_url?`<img class="shop-logo" src="${s.logo_url}">`:''}<h2>${esc(s.title)}</h2><p class="small">${esc(s.description)}</p><span class="badge">Minecraft Store</span></aside><main class="shop-main"><section class="shop-hero"><h1>${esc(s.hero_name||s.title)}</h1><p>${esc(s.description)}</p>${s.banner_url?`<img class="banner" src="${s.banner_url}">`:''}</section><section class="shop-grid">${publicItems.map(i=>`<article class="shop-item">${i.image_url?`<img src="${i.image_url}">`:''}<h3>${esc(i.name)}</h3><p class="small">${esc(i.description)}</p><b>$${esc(i.price)}</b><button class="btn full" style="background:${s.button_color};color:${s.text_color}" onclick="addCart(${i.id})">${esc(i.button_text||'Add to Cart')}</button></article>`).join('')}</section></main><aside class="shop-cart"><h2>Checkout</h2><div id="cartList"></div><div class="field"><label>Minecraft Name</label><input id="mcName" placeholder="Player name"></div><div class="field"><label>Edition</label><select id="edition"><option>Java</option><option>Bedrock</option></select></div><div class="field"><label>Phone Number</label><input id="phone" placeholder="+855..."></div><button class="ghost full" onclick="sendOtp()">Send OTP</button><div class="field"><input id="otp" placeholder="OTP code"></div><button class="ghost full" onclick="verifyOtp()">Verify OTP</button>${s.qr_url?`<h3>Scan QR</h3><img class="qr" src="${s.qr_url}">`:''}<div class="field"><label>Payment Proof</label><input id="proof" type="file" accept="image/*"></div><button class="btn full" onclick="submitOrder()">Submit Order</button></aside></div>`;renderCart()}
function addCart(id){const it=publicItems.find(x=>x.id===id);if(!it)return;const row=cart.find(x=>x.id===id);row?row.qty++:cart.push({id,qty:1});toast('Added to cart');renderCart()}
function renderCart(){const el=$('cartList');if(!el)return;let total=0;el.innerHTML=cart.map(c=>{const i=publicItems.find(x=>x.id===c.id);const sub=(parseFloat(i?.price)||0)*c.qty;total+=sub;return`<div class="cart-line"><span>${esc(i?.name)} x${c.qty}</span><b>$${sub.toFixed(2)}</b></div>`}).join('')+`<div class="cart-line"><b>Total</b><b>$${total.toFixed(2)}</b></div>`}
async function sendOtp(){const j=await api('/api/otp/send',{method:'POST',headers:{authorization:''},body:JSON.stringify({phone:$('phone').value})});if(j.ok)toast('OTP: '+(j.dev_code||'sent'))}
async function verifyOtp(){const j=await api('/api/otp/verify',{method:'POST',headers:{authorization:''},body:JSON.stringify({phone:$('phone').value,code:$('otp').value})});if(j.ok){otpToken=j.otp_token;toast('Phone verified')}}
async function submitOrder(){if(!cart.length)return toast('Cart empty');if(!otpToken)return toast('Verify phone first');const proof=await publicUpload($('proof').files[0]);const j=await api('/api/orders',{method:'POST',headers:{authorization:''},body:JSON.stringify({site_id:publicSite.id,cart,minecraft_name:$('mcName').value,edition:$('edition').value,otp_token:otpToken,payment_proof_url:proof})});if(j.ok){cart=[];toast('Order submitted');renderCart()}}
window.addEventListener('DOMContentLoaded',()=>{hydrateNav();initDrops();if($('email')&&localStorage.getItem('last_email'))$('email').value=localStorage.getItem('last_email')});
